updated 'config' script
- added --list and --query options
- added help
- updated zsh completion
- vim integration

pro.vim: since there is a name conflict, renamed command :Config to :Pro

diff --git a/.local/bin/config b/.local/bin/config
--- a/.local/bin/config
+++ b/.local/bin/config
@@ -1,18 +1,61 @@
 #!/bin/bash
-optfile="$HOME/.config/shortcuts/config"
 
-if [ -z "$1" ]; then
-    opts=$(dictionary keys "$optfile")
-    echo "$opts" | awk '{ print NR ") " $0 }'
-    read -rp "select: " x
-    opt=$(echo "$opts" | awk "NR == $x { print \$0; exit }")
-elif [ "$1" = '--edit' ]; then
-    exec $EDITOR "$optfile"
-else
-    opt="$1"
+optfile="$HOME/.config/shortcuts/config"
+query_mode=1
+
+log() { echo "$@" >&2; }
+die() { log "$@"; exit 1; }
+
+print_help() {
+    log 'Usage: config [-q] [-i|-e|-l|<config>]'
+    log
+    log '  <config>               -- select config'
+    log '  -l, --list             -- print config list'
+    log '  -e, --edit             -- edit config list'
+    log '  -i, --interactive      -- select config interactively'
+    log '  -q, --query            -- print the output and exit'
+    exit 1
+}
+
+run() {
+    if [ "$query_mode" -ne 0 ]; then
+        exec $EDITOR "$1"
+    else
+        echo "$1"
+        exit 0
+    fi
+}
+
+match_and_run() {
+    file=$(dictionary "$optfile" "$1" 2>/dev/null | sed "s|^~/|$HOME/|")
+    [ -z "$file" ] && die 'Option not found'
+    run "$file"
+}
+
+[ -z "$1" ] && print_help
+
+if [ "$1" = '-q' ] || [ "$1" = '--query' ]; then
+    query_mode=0
+    shift
 fi
 
-file=$(dictionary "$optfile" $opt 2>/dev/null | sed "s|^~/|$HOME/|")
-[ -z "$file" ] && echo "option not found" >&2 && exit 1
+[ -z "$1" ] && print_help
 
-exec $EDITOR "$file"
+if [ "$1" = '-i' ] || [ "$1" = '--interactive' ]; then
+    opts=$(dictionary keys "$optfile")
+    (echo "$opts" | awk '{ print NR ") " $0 }') >&2
+    read -rp "Select: " x
+    opt=$(echo "$opts" | awk "NR == $x { print \$0; exit }")
+    match_and_run "$opt"
+fi
+
+if [ "$1" = '-e' ] || [ "$1" = '--edit' ]; then
+    run "$optfile"
+fi
+
+if [ "$1" = '-l' ] || [ "$1" = '--list' ]; then
+    dictionary keys "$optfile"
+    exit $?
+fi
+
+match_and_run "$1"
